backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # Hier landen die Bilder im Repo
public_folder: "/uploads"      # So greift die Website später auf die Bilder zu

collections:
  - name: "events"
    label: "Events"
    folder: "src/pages/events" # Hier speichert das CMS die Markdown-Dateien ab
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Beschreibung", name: "body", widget: "markdown"}
